default_config:
#Odkurzacz
vacuum:
  - platform: miio2
    host: 192.168.X.X
    token: XXX
    name: syzyf

input_select:
  vacuum_room:
    name: Wybierz pomieszczenie
    options:
      - gabinet
      - kuchnia
      - łazienka
      - przedpokój
      - salon
      - sypialnia

#################################### XIAOMI VACUUM ##################################################################
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: Status
          - vacuum.syzyf
        value_template: "{{ states.vacuum.syzyf.attributes.status }}"
        icon_template: >
          {% set val =  states.vacuum.syzyf.attributes.status  %}
          {% if val == 'docked' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
        friendly_name: Fan Speed
        value_template: "{{ states.vacuum.syzyf.attributes.fan_speed }}"
        icon_template: "mdi:speedometer"
      vacuum_battery:
        friendly_name: Bateria
        value_template: "{{ states.vacuum.syzyf.attributes.battery_level }}"
        unit_of_measurement: "%"
        icon_template: "{{ states.vacuum.syzyf.attributes.battery_icon }}"
      vacuum_cleaning_time:
        friendly_name: Time of Last Cycle
        value_template: "{{ states.vacuum.syzyf.attributes.s_time }}"
        icon_template: "mdi:timer"
      vacuum_cleaned_area:
        friendly_name: Area of Last Cycle
        unit_of_measurement: "m²"
        value_template: "{{ states.vacuum.syzyf.attributes.s_area }}"
        icon_template: "mdi:ruler"
      # vacuum_cleanmainbrush:
      #   friendly_name: Replace main brush
      #   unit_of_measurement: "%"
      #   value_template: "Główna szczotka: {{ states.vacuum.syzyf.attributes.main_brush_hours }}"
      #   icon_template: "mdi:screwdriver"
      # vacuum_cleansidebrush:
      #   friendly_name: Replace side brush
      #   unit_of_measurement: "%"
      #   value_template: "Boczna szczotka: {{ states.vacuum.syzyf.attributes.side_brush_hours }}"
      #   icon_template: "mdi:screwdriver"
      # vacuum_cleanfilter:
      #   friendly_name: Replace filter
      #   unit_of_measurement: "%"
      #   value_template: "Filtr: {{ states.vacuum.syzyf.attributes.hypa_hours }}"
      #   icon_template: "mdi:screwdriver"
      # vacuum_sensordirtyleft:
      #   friendly_name: Replace mop
      #   unit_of_measurement: "%"
      #   value_template: "Mop: {{ states.vacuum.syzyf.attributes.mop_hours }}"
      #   icon_template: "mdi:screwdriver"
      vacuum_mop:
        friendly_name: Is mop installed
        value_template: >-
          {% if states.vacuum.syzyf.attributes.mop_type == 1 %}
            Gotowy
          {% else %}
            Brak
          {% endif %}
        icon_template: "mdi:screwdriver"
      vacuum_dustbox:
        friendly_name: dustbox type
        value_template: >-
          {% if states.vacuum.syzyf.attributes.box_type == 1  %}
            Zwykły
          {% elif states.vacuum.syzyf.attributes.box_type == 3  %}
            Z wodą
          {% else %}
            Brak
          {% endif %}
        icon_template: "mdi:screwdriver"
      vacuum_cleanmode:
        friendly_name: Cleaning Mode
        value_template: >-
          {% if states.vacuum.syzyf.attributes.is_mop == 0  %}
            Odkurzanie 
          {% elif states.vacuum.syzyf.attributes.is_mop == 1  %}
            Odkurzanie & Mop
          {% elif states.vacuum.syzyf.attributes.is_mop == 2  %}
            Mop
          {% else %}
            Nie gotowy
          {% endif %}
        icon_template: "mdi:screwdriver"
      vacuum_watergrade:
        friendly_name: ilość wody
        value_template: >-
          {% if states.vacuum.syzyf.attributes.water_grade == 11  %}
            Ilość wody: Mała
          {% elif states.vacuum.syzyf.attributes.water_grade == 12  %}
            Ilość wody: Średnia
          {% elif states.vacuum.syzyf.attributes.water_grade == 13  %}
            Ilość wody: Duża
          {% else %}
            Ilość wody: brak
          {% endif %}
      vacuum_led:
        value_template: >-
          {% if states.vacuum.syzyf.attributes.light_state == 0  %}
            LED wyłączone
          {% else %}
            LED włączone
          {% endif %}
        friendly_name: LED
        icon_template: >-
          {% if states.vacuum.syzyf.attributes.light_state == 0  %}
          mdi:led-variant-off
          {% else %}
          mdi:led-on
          {%- endif %}
      vacuum_volume:
        friendly_name: Głośność
        unit_of_measurement: "%"
        value_template: "{{ states.vacuum.syzyf.attributes.v_state*10 }}"
        icon_template: "mdi:volume-source"
###################################### XIAOMI VACUUM END ##############################################################